### ISSUE TITLE
Compilation error on file lib/mex/cli.ex

### ISSUE THREAD

**Issue by HusseinMorsy** [mrluc/mex#1]
I got an compilation error:

```
** (SyntaxError) lib/mex/cli.ex:19: unexpected comma. Parentheses are required to solve ambiguity in nested calls. Syntax error before: ','
    (elixir) lib/kernel/parallel_compiler.ex:97: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

Using mex, "~> 0.0.1" with Elixir 1.0.5

**Comment by mrluc** [comment]
Out of curiousity, are you on Elixir 1.0 or 1.1-beta? 

I added parens and bumped to 0.0.2. Let me know if it works for you after `mix deps.update mex`

**Comment by HusseinMorsy** [comment]
I'm using elixir 1.0.5.

your last commit fixed the compile error on line 19. But now I got the same error message on line 50.

```
** (SyntaxError) lib/mex/cli.ex:50: unexpected comma. Parentheses are required to solve ambiguity in nested calls. Syntax error before: ','
    (elixir) lib/kernel/parallel_compiler.ex:97: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

**Comment by mrluc** [comment]
Thank you! Serves me right for developing on 1.1, I suppose. Need an Elixir `virtualenv` to switch versions. 

I removed all single-line defs from CLI and bumped to 0.0.3 on hex.

**Comment by HusseinMorsy** [comment]
Great ! I's working now. Mex is a really useful tool. Thanks!
